### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by xmikos** [xoviat/subzero#58]
I see that *subzero* is GPL. This is not problem for my open source projects, but I plan to use it also for one commercial project in future. In PyInstaller there is explicit GPL exception that you can use executables created with it even if the app is proprietary. Does this exception also apply to *subzero*? Maybe it should be explicitly mentioned in README.

**Comment by xoviat** [comment]
Subzero is intended to be licensed under the same licensing standards as PyInstaller. My intention is that executables produced can be used to make money, but not that subzero itself could be sold. I will clarify that in the license.
