### ISSUE TITLE
Generated MSI installer doesn't respect app name capitalization

### ISSUE THREAD

**Issue by xmikos** [xoviat/subzero#66]
I have e.g. `name="QSpectrumAnalyzer"` in `setup`, but *ProductName* in generated MSI installer has different capitalization: `Qspectrumanalyzer`.

Here is problematic line of code: [windist.py#L298](https://github.com/xoviat/subzero/blob/58a32804bacc2c0459abd9ac43ec0ad14811875e/subzero/windist.py#L298)

**Comment by xoviat** [comment]
Closed in 3fb011dba7f1c593bfe5d3843763e6c51b21789e.

See https://github.com/xoviat/subzero/blob/3fb011dba7f1c593bfe5d3843763e6c51b21789e/subzero/windist.py#L140.
