### ISSUE TITLE
Data files are not added to frozen bundle

### ISSUE THREAD

**Issue by xmikos** [xoviat/subzero#67]
I have tried to add data files to my frozen app like this:

    options={                                                                       
        'build_exe': {                                                              
            'datas': [                                                              
                ['qspectrumanalyzer/qspectrumanalyzer.svg', 'qspectrumanalyzer'],   
                ['qspectrumanalyzer/languages/*.qm', 'qspectrumanalyzer/languages'],
            ],                                                                      
        },
    }

But there are several errors:

1. I had to use lists instead of tuples to specify data files, with tuples it gave me this error:

        File "C:\Program Files\Python36\lib\site-packages\subzero\dist.py", line 132, in run
          options['datas'][i][0] = os.path.abspath(options['datas'][i][0])
        TypeError: 'tuple' object does not support item assignment

2. even if I use lists, it doesn't work, data files are not added to final bundle. But it does work if I try it directly with PyInstaller like this:

        pyinstaller --add-data "qspectrumanalyzer/qspectrumanalyzer.svg;qspectrumanalyzer" --add-data "qspectrumanalyzer/languages/*.qm;qspectrumanalyzer/languages" qspectrumanalyzer/__main__.py

**Comment by xmikos** [comment]
I have looked into it a little. If I comment out rest of `run()` method after `self._freeze()` (from line [dist.py#L156](https://github.com/xoviat/subzero/blob/master/subzero/dist.py#L156) to the end of method) and explore temporary *build/exe* directory, there are two subdirs: `QSpectrumAnalyzer` and `soapy_power` (I have two `console_scripts` in `entry_points`). And data files are there, in both of those subdirs. So something in `move_tree` must be broken (removes data files).

**Comment by xoviat** [comment]
I'm going to implement a test case for this.

**Comment by xmikos** [comment]
Btw. I see in .spec files for second executable (soapy_power) that dependencies from first executable (QSpectrumAnalyzer) are included in hidden imports. Doesn't this make second executable unnecessarily big?

**Comment by xoviat** [comment]
> Btw. I see in .spec files for second executable (soapy_power) that dependencies from first executable (QSpectrumAnalyzer) are included in hidden imports. Doesn't this make second executable unnecessarily big?

As I said before, only bytecode is duplicated. The proper fix for this is to implement MERGE.

**Comment by xmikos** [comment]
But isn't it unnecessary in this case? What would happen if you just freeze second executable without hidden imports from other executables and merge it with move_tree like that?

**Comment by xmikos** [comment]
(I thought that by bytecode duplication you only mean standard library)

**Comment by xmikos** [comment]
I have looked at it again yesterday and I think I have found where the problem is. I am now experimenting with it in my fork and if it will be OK, I will make pull request.
