### ISSUE TITLE
Installer offers "Program Files (x86)" as default path for 64-bit app

### ISSUE THREAD

**Issue by xmikos** [xoviat/subzero#79]
I have built 64-bit app (with 64-bit Python), but MSI installer offers "Program Files (x86)" as default install path.

Btw. could be somehow app icon also added to installer (so that MSI file shows app icon instead of default Windows installer icon)?

**Comment by xoviat** [comment]
> Btw. could be somehow app icon also added to installer (so that MSI file shows app icon instead of default Windows installer icon)?

that's #6. unfortunately, with the switch to go-msi, that's no longer possible without a patch to go-msi. However, I may submit a patch for that within the next few days.
