### ISSUE TITLE
Generated MSI installer has generic name instead of app name

### ISSUE THREAD

**Issue by xmikos** [xoviat/subzero#80]
MSI installer generated in `dist/` has generic name (same as build dir name) instead of using application `name` as specified in `setup`.

**Comment by xoviat** [comment]
Are you referring to the filename of the generated installer?

**Comment by xmikos** [comment]
Yes, only filename seems to be wrong.

**Comment by xoviat** [comment]
would application + build dir name be okay?

**Comment by xmikos** [comment]
IMHO ideal pattern would be something like `AppName-1.2.3-x64.msi` (or `AppName-1.2.3.msi` for 32-bit builds). But to be fair, this really isn't important to me, I can rename it myself ;-)

**Comment by xoviat** [comment]
yeah, that's fine. I'm not going to have appname.msi though because then you can't tell the version or build arch.
