### ISSUE TITLE
subzero only works with Python 3+

### ISSUE THREAD

**Issue by mbrennan** [xoviat/subzero#93]
It seems `subzero` depends on `pywix`, which depends on Python 3's `functools`.  I've created an issue on the `pywix` GitHub page here:  xoviat/pywix#4

**Comment by xoviat** [comment]
Actually we're not doing this until someone backports the mypy codec. I am not going to preclude type annotations for this project.

**Comment by mbrennan** [comment]
That's fine, but can you mark the package appropriately so it requires Python 3?  It'd be better to have the installation fail rather than the next guy or gal try to figure out why it's not working with Python 2.7.
